language: csharp
solution: Hangfire.Raven.sln
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required
script:
 - dotnet restore
 - dotnet build -f netstandard1.3
 - dotnet build -f netstandard1.4
 - dotnet build -f netstandard1.5
 - dotnet build -f netstandard1.6
 - dotnet build -f netstandard2.0