language: csharp
solution: Hangfire.Raven.sln
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required
script:
 - dotnet restore
 - dotnet build -f netstandard1.3  ./src/Hangfire.Raven/Hangfire.Raven.csproj
 - dotnet build -f netstandard1.4  ./src/Hangfire.Raven/Hangfire.Raven.csproj
 - dotnet build -f netstandard1.5  ./src/Hangfire.Raven/Hangfire.Raven.csproj
 - dotnet build -f netstandard1.6  ./src/Hangfire.Raven/Hangfire.Raven.csproj
 - dotnet build -f netstandard2.0  ./src/Hangfire.Raven/Hangfire.Raven.csproj